version: '3'

networks:
  net:

services:
  php:
    build: .
    container_name: php74
    volumes:
      - ./magento2:/magento2
    working_dir: /magento2
    expose:
      - 9000
    networks:
      - net
    restart: unless-stopped

  mariadb:
    image: mariadb
    container_name: mariadb
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      - /data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: magento2
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - net
    restart: unless-stopped

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:433
    volumes:
      - ./magento2:/var/www/html
      - ./magento2.conf/:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mariadb
    networks:
      - net
    restart: unless-stopped
